### ISSUE TITLE
Usage of azlyrics

### ISSUE THREAD

**Issue by ramonsaraiva** [mhtghn/Luricifer#4]
Is there any special reason you are copying the files contents from the azlyrics repository instead of pipping it?

If not, i'm happy to make another pull request using the repository properly, reducing the amount of duplicated code in Luricifer :-)

**Comment by mhtghn** [comment]
No reason at all. I did it to see if it worked the way I wanted it to work. But now I agree that we should just pip it.
Yes you can make the PR :+1:
